### PR TITLE
Support for Mongo.ObjectID 

### PR DESCRIPTION
**Pull request by RealHandy**
Rob, per your guidance in issue https://github.com/robfallows/tunguska-reactive-aggregate/issues/34, I've added code in my fork that makes the package (hopefully automatically) work with Mongo.ObjectIDs, rather than just string object ids. It uses the simple-schema that comes in the collection.schema, traverses it once at the start of the aggregation to find all the Mongo.ObjectID fields, remembers those, and then repairs each doc's damaged ObjectIDs back from being MongoInternals.NpmModule.ObjectIDs. I've tried to make it perform efficiently while also using the existing simple-schema functions to get the job done with as little new code as possible. I left the doc_id key used in sub._ids a string, but the code is obviously no longer converting ids themselves to strings if they are Mongo.ObjectIDs.

### CODE REVIEW

**Comment by robfallows** [comment]
Thanks for the PR - it's a novel way of addressing the issue 🙂. The documentation changes and code quality are great 👍 . However, not everyone uses simple schema and adding it as a requirement may introduce breaking changes to existing code. At the very least, that would require a major version bump.

Alternatively, would it be possible to make use of a weak dependency on simple schema - if it's present use it, otherwise fall back to using `objectIDKeysToRepair`?

I'm less concerned about breaking changes, with `lodash` - although I'm wondering if are there native ES6/7 ways of doing `set`?

**Comment by RealHandy** [comment]
Hey, back again. Per your comments, I made these additional mods:

- simpl-schema and lodash are now optional. if they aren't both loaded, the server console logs that Mongo.ObjectID support is disabled due to any package load errors, and lists them like this
```
ReactiveAggregate support for Mongo.ObjectID is disabled due to 2 package error(s):
    1 - lodash-es or lodash: lodash-es(MODULE_NOT_FOUND), lodash(MODULE_NOT_FOUND)
    2 - simpl-schema: MODULE_NOT_FOUND
```
- now uses either lodash-es or lodash
- readme now reflects the optional loading and explains more about what's up with it

**Comment by RealHandy** [comment]
I looked at a number of other dotted path key handling packages and algorithms, but so many seem iffy, and lodash is rock solid in comparison, so I went with it.

**Comment by robfallows** [comment]
This is looking good. Can you bump the version in `package.js` to `1.3.0`, please?

**Comment by RealHandy** [comment]
Done. Apologies for the sloppy ".0"-less initial push of the version :P

**Comment by RealHandy** [comment]
Great. Thanks, Rob!

**Pull request merged**
