### PR TITLE
Meteor 3 Ready and optionally Function for Pipeline param

### PR DESCRIPTION
**Pull request by JanMP**
- merged async-code into master
- pipeline parameter may now be a function returning a pipeline. If this is the case then the pipeline will be regenerated on update (e.g. allow for $match phase to depend on alannning:roles)

### CODE REVIEW

**Review by robfallows — COMMENTED** [review]
Looking good 👍 

Please also update `README.md` and `History.md`

Thank you!

**Comment by JanMP** [comment]
What Version should I bump it to? 1.4? 2.0?

**Comment by robfallows** [comment]
> What Version should I bump it to? 1.4? 2.0?

I would think 2.0.0 given it's a major breaking change.

**Review by robfallows — APPROVED** [review]
LGTM 👍

**Comment by alisnic** [comment]
any eta when new package version will be published? version 2.0.0 is not on https://atmospherejs.com/

**Comment by robfallows** [comment]
Weird. I thought I'd done that. Now done - but I notice the README needs an update. I'll try and update that soon.

**Comment by alisnic** [comment]
> Weird. I thought I'd done that. Now done - but I notice the README needs an update. I'll try and update that soon.

Thank you!

**Pull request merged**
