### PR TITLE
Ensure Mongo ObjectIDs are converted to strings before tracking.

### LINKED ISSUE #3: Meteor does not currently support objects other than ObjectID as ids
Having an issue, wondering what I am doing wrong. Maybe its due to using Mongo Ids as the _id?

Code:
```javascript

    if (Meteor.isServer) {
      let options: any = {idGeneration: 'MONGO', 'defineMutationMethods': true};
      let model = new Mongo.Collection('epColl', options);
      let episodeSelector = [
        {$limit:50} 
      ]; //simplified

      Meteor.publish('subscribeTop20', function () {
        ReactiveAggregate(this, model, episodeSelector);
      });
    }

```

Exception:

Exception from sub OuNeRe_subscribeTop20 id 6w6yJPEj3Smp5bYhy Error: Meteor does not currently support objects other than ObjectID as ids
I20180905-19:50:23.759(-4)?     at Object.MongoID.idStringify.id [as idStringify] (packages/mongo-id/id.js:77:11)
I20180905-19:50:23.760(-4)?     at Subscription.added (packages/ddp-server/livedata_server.js:1254:25)
I20180905-19:50:23.760(-4)?     at docs.forEach.doc (packages/tunguska:reactive-aggregate/aggregate.js:22:15)
I20180905-19:50:23.760(-4)?     at Array.forEach (<anonymous>)
I20180905-19:50:23.760(-4)?     at Promise.asyncApply (packages/tunguska:reactive-aggregate/aggregate.js:20:12)
I20180905-19:50:23.760(-4)?     at /home/jerrad/.meteor/packages/promise/.0.11.1.1q584qp.8ndl++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20180905-19:50:23.760(-4)?  => awaited here:
I20180905-19:50:23.761(-4)?     at Function.Promise.await (/home/jerrad/.meteor/packages/promise/.0.11.1.1q584qp.8ndl++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20180905-19:50:23.761(-4)?     at Object.ReactiveAggregate (packages/tunguska:reactive-aggregate/aggregate.js:56:3)
I20180905-19:50:23.761(-4)?     at Subscription._handler (collections/OuNeRe.ts:46:9)
I20180905-19:50:23.761(-4)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
I20180905-19:50:23.762(-4)?     at DDP._CurrentPublicationInvocation.withValue (packages/ddp-server/livedata_server.js:1043:15)
I20180905-19:50:23.762(-4)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)
I20180905-19:50:23.762(-4)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1041:51)
I20180905-19:50:23.762(-4)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:859:9)
I20180905-19:50:23.762(-4)?     at Session.sub (packages/ddp-server/livedata_server.js:625:12)
I20180905-19:50:23.762(-4)?     at packages/ddp-server/livedata_server.js:559:43

### PR DESCRIPTION
**Pull request by robfallows**
Closes #3.

To test this PR:

1. Create a `packages` folder in your project's root, if you don't already have one.
1. `cd packages`
1. `git clone git@github.com:robfallows/tunguska-reactive-aggregate.git`
1. `git checkout bugfix/track-object-ids-better`
1. `cd ..`
1. `meteor run`

You should see that Meteor reports an update to `tunguska:reactive-aggregate`.

You now need to run any tests that were failing before the package update.

### CODE REVIEW

**Comment by jerradpatch** [comment]
So, I am just getting time to get back to this. Thanks for the work, but I cannot get it to run with this PR either. I get this:

Exception from sub OuNeRe_subscribeTop20 id e9o3avw9nvNf4QssH Error: Meteor does not currently support objects other than ObjectID as ids
I20181017-20:28:15.715(-4)?     at Object.MongoID.idStringify.id [as idStringify] (packages/mongo-id/id.js:77:11)
I20181017-20:28:15.716(-4)?     at Subscription.added (packages/ddp-server/livedata_server.js:1254:25)
I20181017-20:28:15.716(-4)?     at docs.forEach.doc (packages/tunguska:reactive-aggregate/aggregate.js:23:15)
I20181017-20:28:15.717(-4)?     at Array.forEach (<anonymous>)
I20181017-20:28:15.717(-4)?     at Promise.asyncApply (packages/tunguska:reactive-aggregate/aggregate.js:20:12)
I20181017-20:28:15.717(-4)?     at /home/jerrad/.meteor/packages/promise/.0.11.1.1vczms8.mxi5++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20181017-20:28:15.718(-4)?  => awaited here:
I20181017-20:28:15.718(-4)?     at Function.Promise.await (/home/jerrad/.meteor/packages/promise/.0.11.1.1vczms8.mxi5++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20181017-20:28:15.718(-4)?     at Object.ReactiveAggregate (packages/tunguska:reactive-aggregate/aggregate.js:57:3)
I20181017-20:28:15.718(-4)?     at Subscription._handler (collections/OuNeRe.ts:50:9)

**Comment by robfallows** [comment]
@jerradpatch : can you run `meteor list` and paste the output here, please?

**Comment by jerradpatch** [comment]
@robfallows 

accounts-base                1.4.3  A user account system
accounts-facebook            1.3.2  Login service for Facebook accounts
accounts-google              1.3.2  Login service for Google accounts
angular-compilers            0.3.2  Rollup, AOT, SCSS, HTML and TypeScript compilers for Angular Meteor
ecmascript                   0.12.1  Compiler plugin that supports ES2015+ in all .js files
es5-shim                     4.8.0  Shims and polyfills to improve ECMAScript 5 support
fortawesome:fontawesome      4.7.0  Font Awesome (official): 500+ scalable vector icons, customizable via CSS, Retina friendly
meteor-base                  1.4.0  Packages that every Meteor app needs
mobile-experience            1.0.5  Packages for a great mobile user experience
mongo                        1.6.0  Adaptor for using MongoDB and Minimongo over DDP
reactive-var                 1.0.11  Reactive variable
reywood:publish-composite    1.7.0  Publish a set of related documents from multiple collections with a reactive join
sakulstra:aggregate          1.4.3  Proper MongoDB aggregations support for Meteor
service-configuration        1.0.11  Manage the configuration for third-party services
shell-server                 0.4.0  Server-side component of the `meteor shell` command.
standard-minifier-css        1.5.1  Standard css minifier used with Meteor apps by default.
standard-minifier-js         2.4.0  Standard javascript minifiers used with Meteor apps by default.
tracker                      1.2.0  Dependency tracker to allow reactive callbacks
tunguska:reactive-aggregate  1.0.4+ Reactively publish aggregations.
vsivsi:file-collection       1.3.5* Collections that efficiently store files using MongoDB GridFS, with built-in HTTP support

**Comment by robfallows** [comment]
@jerradpatch : do you get this error using the simplified pipeline you used in your example?

I ask, because, I cannot duplicate that error.

I can get an error if I use a pipeline which does not emit `_id`s (for example, if I use `[{ $count: 'doc_count' }]`. However, even that error is not the same as yours.

**Comment by robfallows** [comment]
Closing due to lack of feedback.

**Comment by ShaggyKris** [comment]
@robfallows 

I am currently experiencing this issue.

```
accounts-password                1.5.1  Password support for accounts
alanning:roles                   1.2.16  Authorization package for Meteor
aldeed:collection2               3.0.2  Automatic validation of Meteor Mongo insert and update operations on the client and server
aldeed:simple-schema             1.5.4  A simple schema validation object with reactivity. Used by collection2 and autoform.
blaze-html-templates             1.1.2  Compile HTML templates into reactive UI with Meteor Blaze
check                            1.3.1  Check whether a value matches a pattern
dburles:collection-helpers       1.1.0  Transform your collections with helpers that you define
dburles:factory                  1.1.0  Factories for Meteor
ddp-rate-limiter                 1.0.7  The DDPRateLimiter allows users to add rate limits to DDP methods and subscriptions.
ecmascript                       0.12.7  Compiler plugin that supports ES2015+ in all .js files
email                            1.2.3  Send email messages
es5-shim                         4.8.0  Shims and polyfills to improve ECMAScript 5 support
http                             1.4.2  Make HTTP calls to remote servers
insecure                         1.0.7  (For prototyping only) Allow all database writes from the client
matb33:collection-hooks          0.8.4  Extends Mongo.Collection with before/after hooks for insert/update/remove/find/findOne
maximum:server-transform         0.5.0  Meteor package to transform documents on publish
mdg:seo                          3.2.1_1  Provide SEO support for enabled apps.
mdg:validated-method             1.2.0  A simple wrapper for Meteor.methods
meteor-base                      1.4.0  Packages that every Meteor app needs
meteorhacks:aggregate            1.3.0  Proper MongoDB aggregations support for Meteor
mobile-experience                1.0.5  Packages for a great mobile user experience
mongo                            1.6.2* Adaptor for using MongoDB and Minimongo over DDP
msavin:sjobs                     3.1.1  The simple jobs queue that just works [synced, schedule, tasks, background, later, worker, cron]
ostrio:files                     1.10.2* File upload via DDP/HTTP to server, 3rd party storage support: AWS S3, GridFS, DropBox and others
percolate:find-from-publication  0.2.0* Enable finding all documents that have been published by a given publication
promise                          0.11.2  ECMAScript 2015 Promise polyfill with Fiber support
react-meteor-data                0.2.16  React higher-order component for reactively tracking Meteor data
reactive-var                     1.0.11  Reactive variable
reywood:publish-composite        1.7.0* Publish a set of related documents from multiple collections with a reactive join
ros:publish-counts               0.5.1  Publish the count of a cursor, in real time.  Supports large collections.
server-render                    0.3.1  Generic support for server-side rendering in Meteor apps
session                          1.2.0  Session variable
shell-server                     0.4.0  Server-side component of the `meteor shell` command.
simple:reactive-method           1.0.2  Call methods synchronously inside Tracker.autorun
standard-minifier-css            1.5.3  Standard css minifier used with Meteor apps by default.
standard-minifier-js             2.4.1  Standard javascript minifiers used with Meteor apps by default.
tracker                          1.2.0  Dependency tracker to allow reactive callbacks
tunguska:reactive-aggregate      1.1.0  Publish aggregations reactively
twbs:bootstrap                   3.3.6  The most popular front-end framework for developing responsive, mobile first projects on the web.
underscore                       1.0.10  Collection of small helpers: _.map, _.each, ...
```

My aggregation pipeline seems to work when I query it in Robo3T. If you need further info please ask.

**Comment by robfallows** [comment]
@ShaggyKris : can you provide a minimal repro which I can use to test with?
Thanks.

**Comment by ShaggyKris** [comment]
> @ShaggyKris : can you provide a minimal repro which I can use to test with?
> Thanks.

As this is a client project, I'll have to make one which will take a tiny bit of time. Unless you have another suggestion?

**Comment by ShaggyKris** [comment]
@robfallows 

https://github.com/ShaggyKris/template-repo

**Comment by robfallows** [comment]
I now have a slightly clearer understanding of what's going on here. At the moment, this is only an observation, so take my comments with a pinch of salt:

`ObjectId`s from the MongoDB `collection#aggregate` method do not seem to be handled nicely by the `aggregationCursor#toArray` method and end up not being understood by minimongo. I can get the pipeline and publication working as expected by forcing the `_id`s to strings in the pipeline. For example in the `$project` stage:

```
        $project: {
          _id: { $toString: '$_id' },
          waggleEditorUser: 1,
          clinics: 1,
          totalFunded: 1,
          totalRequested: 1,
          startDate: 1,
          endDate: 1,
          campaignStatus: 1,
          userSubmitted: 1,
          writerDone: 1,
          facebookShares: 1,
          sponsors: 1,
          clinicTemp: 1,
          state: 1,
          healthStatus: 1,
          getCampaignURL: 1,
          infoDone: 1,
          storyDone: 1,
          imageDone: 1,
          treatmentDone: 1,
          returnStatus: 1,
          petsObj: { $arrayElemAt: ["$petsObj", 0] },
          clinicObj: { $arrayElemAt: ["$clinicObj", 0] },
        },
```

For now, I suggest you do something like that, while I consider the best way of handling `_id`s generally.

**Comment by robfallows** [comment]
Closing this PR.

Will open a new one to address the issues found here.

**Comment by robfallows** [comment]
@jerradpatch : you may find the workaround documented above works for you as well.

**Comment by ShaggyKris** [comment]
@robfallows 

Getting this error when using `$toString` and deployed on Galaxy:

```
Exception from sub campaignDashboardAggregation id mLXLzz3orto2w4feQ { Error: Unrecognized expression '$toString'
fwxfr
2019-08-13 15:07:47-03:00 at update (packages/tunguska:reactive-aggregate/aggregate.js:116:13)
fwxfr
2019-08-13 15:07:47-03:00 at ReactiveAggregate (packages/tunguska:reactive-aggregate/aggregate.js:155:3)
fwxfr
2019-08-13 15:07:47-03:00 at Subscription.<anonymous> (imports/startup/server/publications.js:1508:5)
fwxfr
2019-08-13 15:07:47-03:00 at packages/matb33_collection-hooks.js:307:21
fwxfr
2019-08-13 15:07:47-03:00 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
fwxfr
2019-08-13 15:07:47-03:00 at Subscription._handler (packages/matb33_collection-hooks.js:306:28)
fwxfr
2019-08-13 15:07:47-03:00 at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
fwxfr
2019-08-13 15:07:47-03:00 at DDP._CurrentPublicationInvocation.withValue (packages/ddp-server/livedata_server.js:1046:15)
fwxfr
2019-08-13 15:07:47-03:00 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
fwxfr
2019-08-13 15:07:47-03:00 at Subscription._runHandler (packages/ddp-server/livedata_server.js:1044:51)
fwxfr
2019-08-13 15:07:47-03:00 at Session._startSubscription (packages/ddp-server/livedata_server.js:860:9)
fwxfr
2019-08-13 15:07:47-03:00 at Session.sub (packages/ddp-server/livedata_server.js:625:12)
fwxfr
2019-08-13 15:07:47-03:00 at packages/ddp-server/livedata_server.js:559:43
fwxfr
2019-08-13 15:07:47-03:00 message: 'Unrecognized expression \'$toString\'',
fwxfr
2019-08-13 15:07:47-03:00 path: '',
fwxfr
2019-08-13 15:07:47-03:00 sanitizedError:
fwxfr
2019-08-13 15:07:47-03:00 { Error: tunguska:reactive-aggregate [Error]
fwxfr
2019-08-13 15:07:47-03:00 at errorClass.<anonymous> (packages/tunguska:reactive-aggregate/aggregate.js:10:27)
fwxfr
2019-08-13 15:07:47-03:00 at new errorClass (packages/meteor.js:655:17)
fwxfr
2019-08-13 15:07:47-03:00 at update (packages/tunguska:reactive-aggregate/aggregate.js:116:13)
fwxfr
2019-08-13 15:07:47-03:00 at ReactiveAggregate (packages/tunguska:reactive-aggregate/aggregate.js:155:3)
fwxfr
2019-08-13 15:07:47-03:00 at Subscription.<anonymous> (imports/startup/server/publications.js:1508:5)
fwxfr
2019-08-13 15:07:47-03:00 at packages/matb33_collection-hooks.js:307:21
fwxfr
2019-08-13 15:07:47-03:00 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
fwxfr
2019-08-13 15:07:47-03:00 at Subscription._handler (packages/matb33_collection-hooks.js:306:28)
fwxfr
2019-08-13 15:07:47-03:00 at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
fwxfr
2019-08-13 15:07:47-03:00 at DDP._CurrentPublicationInvocation.withValue (packages/ddp-server/livedata_server.js:1046:15)
fwxfr
2019-08-13 15:07:47-03:00 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
fwxfr
2019-08-13 15:07:47-03:00 at Subscription._runHandler (packages/ddp-server/livedata_server.js:1044:51)
fwxfr
2019-08-13 15:07:47-03:00 at Session._startSubscription (packages/ddp-server/livedata_server.js:860:9)
fwxfr
2019-08-13 15:07:47-03:00 at Session.sub (packages/ddp-server/livedata_server.js:625:12)
fwxfr
2019-08-13 15:07:47-03:00 at packages/ddp-server/livedata_server.js:559:43
fwxfr
2019-08-13 15:07:47-03:00 isClientSafe: true,
fwxfr
2019-08-13 15:07:47-03:00 error: 'Error',
fwxfr
2019-08-13 15:07:47-03:00 reason: 'tunguska:reactive-aggregate',
fwxfr
2019-08-13 15:07:47-03:00 details: undefined,
fwxfr
2019-08-13 15:07:47-03:00 message: 'tunguska:reactive-aggregate [Error]',
fwxfr
2019-08-13 15:07:47-03:00 errorType: 'Meteor.Error' },
fwxfr
2019-08-13 15:07:47-03:00 errorType: 'tunguska:reactive-aggregate' }
fwxfr
2019-08-13 15:07:47-03:00Sanitized and reported to the client as: { Error: tunguska:reactive-aggregate [Error]
fwxfr
2019-08-13 15:07:47-03:00 at errorClass.<anonymous> (packages/tunguska:reactive-aggregate/aggregate.js:10:27)
fwxfr
2019-08-13 15:07:47-03:00 at new errorClass (packages/meteor.js:655:17)
fwxfr
2019-08-13 15:07:47-03:00 at update (packages/tunguska:reactive-aggregate/aggregate.js:116:13)
fwxfr
2019-08-13 15:07:47-03:00 at ReactiveAggregate (packages/tunguska:reactive-aggregate/aggregate.js:155:3)
fwxfr
2019-08-13 15:07:47-03:00 at Subscription.<anonymous> (imports/startup/server/publications.js:1508:5)
fwxfr
2019-08-13 15:07:47-03:00 at packages/matb33_collection-hooks.js:307:21
fwxfr
2019-08-13 15:07:47-03:00 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
fwxfr
2019-08-13 15:07:47-03:00 at Subscription._handler (packages/matb33_collection-hooks.js:306:28)
fwxfr
2019-08-13 15:07:47-03:00 at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
fwxfr
2019-08-13 15:07:47-03:00 at DDP._CurrentPublicationInvocation.withValue (packages/ddp-server/livedata_server.js:1046:15)
fwxfr
2019-08-13 15:07:47-03:00 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
fwxfr
2019-08-13 15:07:47-03:00 at Subscription._runHandler (packages/ddp-server/livedata_server.js:1044:51)
fwxfr
2019-08-13 15:07:47-03:00 at Session._startSubscription (packages/ddp-server/livedata_server.js:860:9)
fwxfr
2019-08-13 15:07:47-03:00 at Session.sub (packages/ddp-server/livedata_server.js:625:12)
fwxfr
2019-08-13 15:07:47-03:00 at packages/ddp-server/livedata_server.js:559:43
fwxfr
2019-08-13 15:07:47-03:00 isClientSafe: true,
fwxfr
2019-08-13 15:07:47-03:00 error: 'Error',
fwxfr
2019-08-13 15:07:47-03:00 reason: 'tunguska:reactive-aggregate',
fwxfr
2019-08-13 15:07:47-03:00 details: undefined,
fwxfr
2019-08-13 15:07:47-03:00 message: 'tunguska:reactive-aggregate [Error]',
fwxfr
2019-08-13 15:07:47-03:00 errorType: 'Meteor.Error' }
```

Pipeline is as follows:
```
let pipeline = [
        { $sort: { startDate: -1 } },
        {
            $lookup: {
                from: "pets",
                localField: "pets.uuid", // field in the orders collection
                foreignField: "_id", // field in the items collection
                as: "petObj",
            },
        },
        {
            $replaceRoot: {
                newRoot: { $mergeObjects: [{ $arrayElemAt: ["$petObj", 0] }, "$$ROOT"] },
            },
        },
        {
            $lookup: {
                from: "clinics",
                localField: "clinicTemp.clinicEmail", // field in the orders collection
                foreignField: "email", // field in the items collection
                as: "clinicObj",
            },
        },
        {
            $replaceRoot: {
                newRoot: { $mergeObjects: [{ $arrayElemAt: ["$clinicObj", 0] }, "$$ROOT"] },
            },
        },
        {
            $lookup: {
                from: "users",
                localField: "initiator.id", // field in the orders collection
                foreignField: "_id", // field in the items collection
                as: "user",
            },
        },
        {
            $replaceRoot: {
                newRoot: { $mergeObjects: [{ $arrayElemAt: ["$user", 0] }, "$$ROOT"] },
            },
        },
        {
            $project: {
                _id: {
                    $toString: "$_id",
                },
                pets: 1,
                waggleEditorUser: 1,
                clinics: 1,
                totalFunded: 1,
                totalRequested: 1,
                startDate: 1,
                endDate: 1,
                campaignStatus: 1,
                userSubmitted: 1,
                writerDone: 1,
                facebookShares: 1,
                sponsors: 1,
                clinicTemp: 1,
                state: 1,
                healthStatus: 1,
                getCampaignURL: 1,
                infoDone: 1,
                storyDone: 1,
                imageDone: 1,
                treatmentDone: 1,
                returnStatus: 1,
                petObj: { $arrayElemAt: ["$petObj", 0] },
                clinicObj: { $arrayElemAt: ["$clinicObj", 0] },
                user: { $arrayElemAt: ["$user", 0] },
            },
        },
        {
            $addFields: {
                "petObj.pet_id": {
                    $toString: "$petObj._id",
                },
                "clinicObj.clinic_id": {
                    $toString: "$clinicObj._id",
                },
            },
        },
        {
            $project: {
                "petObj._id": 0,
                "clinicObj._id": 0,
            },
        },
        {
            $addFields: {
                "petObj._id": "$petObj.pet_id",
                "clinicObj._id": "$clinicObj.clinic_id",
            },
        },
        {
            $project: {
                "petObj.pet_id": 0,
                "clinicObj.clinic_id": 0,
            },
        },
    ];
```

**Comment by robfallows** [comment]
@jerradpatch , @ShaggyKris : please review #16 in your projects and provide feedback to the PR.

Thank you 🙂

**Pull request closed without merging**
