### PR TITLE
Improve id handling

### LINKED ISSUE #3: Meteor does not currently support objects other than ObjectID as ids
Having an issue, wondering what I am doing wrong. Maybe its due to using Mongo Ids as the _id?

Code:
```javascript

    if (Meteor.isServer) {
      let options: any = {idGeneration: 'MONGO', 'defineMutationMethods': true};
      let model = new Mongo.Collection('epColl', options);
      let episodeSelector = [
        {$limit:50} 
      ]; //simplified

      Meteor.publish('subscribeTop20', function () {
        ReactiveAggregate(this, model, episodeSelector);
      });
    }

```

Exception:

Exception from sub OuNeRe_subscribeTop20 id 6w6yJPEj3Smp5bYhy Error: Meteor does not currently support objects other than ObjectID as ids
I20180905-19:50:23.759(-4)?     at Object.MongoID.idStringify.id [as idStringify] (packages/mongo-id/id.js:77:11)
I20180905-19:50:23.760(-4)?     at Subscription.added (packages/ddp-server/livedata_server.js:1254:25)
I20180905-19:50:23.760(-4)?     at docs.forEach.doc (packages/tunguska:reactive-aggregate/aggregate.js:22:15)
I20180905-19:50:23.760(-4)?     at Array.forEach (<anonymous>)
I20180905-19:50:23.760(-4)?     at Promise.asyncApply (packages/tunguska:reactive-aggregate/aggregate.js:20:12)
I20180905-19:50:23.760(-4)?     at /home/jerrad/.meteor/packages/promise/.0.11.1.1q584qp.8ndl++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20180905-19:50:23.760(-4)?  => awaited here:
I20180905-19:50:23.761(-4)?     at Function.Promise.await (/home/jerrad/.meteor/packages/promise/.0.11.1.1q584qp.8ndl++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20180905-19:50:23.761(-4)?     at Object.ReactiveAggregate (packages/tunguska:reactive-aggregate/aggregate.js:56:3)
I20180905-19:50:23.761(-4)?     at Subscription._handler (collections/OuNeRe.ts:46:9)
I20180905-19:50:23.761(-4)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
I20180905-19:50:23.762(-4)?     at DDP._CurrentPublicationInvocation.withValue (packages/ddp-server/livedata_server.js:1043:15)
I20180905-19:50:23.762(-4)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)
I20180905-19:50:23.762(-4)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1041:51)
I20180905-19:50:23.762(-4)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:859:9)
I20180905-19:50:23.762(-4)?     at Session.sub (packages/ddp-server/livedata_server.js:625:12)
I20180905-19:50:23.762(-4)?     at packages/ddp-server/livedata_server.js:559:43

### PR DESCRIPTION
**Pull request by robfallows**
## Description

See discussion in #4 
Closes #3.

## Testing

To test this PR:

1. Create a `packages` folder in your project's root, if you don't already have one.
1. `cd packages`
1. `git clone git@github.com:robfallows/tunguska-reactive-aggregate.git`
1. `cd tunguska-reactive-aggregate`
1. `git checkout improve-id-handling`
1. `cd ../..`
1. `meteor`

You should see that Meteor reports an update to `tunguska:reactive-aggregate`.

You now need to run any tests that were failing before the package update.

## Feedback

1. Please ensure you provide feedback to this PR as to whether it fixes your issue or not.
1. Please ensure you provide feedback to the PR if it introduces any new issues.

## Release

Following a successful PR review, I will release the updated package to atmosphere. You may then delete the cloned copy of the package from your project.

### CODE REVIEW

**Comment by ShaggyKris** [comment]
```
Kristofers-MacBook-Pro-15:packages kristoferpervin$ git clone git@github.com:robfallows/tunguska-reactive-aggregate.git
Cloning into 'tunguska-reactive-aggregate'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by ShaggyKris** [comment]
@robfallows 

Was able to finally clone it. I have it set up in my `$ProjectRoot/packages` folder. Do it access it as normal, or do I access it directly? If the latter, I'm getting an error saying `Cannot find module '/packages/tunguska-reactive-aggregate'`.

**Comment by ShaggyKris** [comment]
```
I20190814-10:34:56.739(-3)? Exception from sub campaignDashboardAggregation id 3oecjJgHotRTvqRWo { Error: doc_id is not defined
I20190814-10:34:56.739(-3)?     at update (packages/tunguska:reactive-aggregate/aggregate.js:136:13)
I20190814-10:34:56.740(-3)?     at ReactiveAggregate (packages/tunguska:reactive-aggregate/aggregate.js:182:3)
I20190814-10:34:56.740(-3)?     at Subscription.<anonymous> (imports/startup/server/publications.js:1527:5)
I20190814-10:34:56.740(-3)?     at packages/matb33_collection-hooks.js:307:21
I20190814-10:34:56.740(-3)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20190814-10:34:56.740(-3)?     at Subscription._handler (packages/matb33_collection-hooks.js:306:28)
I20190814-10:34:56.740(-3)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
I20190814-10:34:56.741(-3)?     at DDP._CurrentPublicationInvocation.withValue (packages/ddp-server/livedata_server.js:1046:15)
I20190814-10:34:56.741(-3)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20190814-10:34:56.741(-3)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1044:51)
I20190814-10:34:56.741(-3)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:860:9)
I20190814-10:34:56.741(-3)?     at Session.sub (packages/ddp-server/livedata_server.js:625:12)
I20190814-10:34:56.741(-3)?     at packages/ddp-server/livedata_server.js:559:43
I20190814-10:34:56.742(-3)?   message: 'doc_id is not defined',
I20190814-10:34:56.742(-3)?   path: '',
I20190814-10:34:56.742(-3)?   sanitizedError: 
I20190814-10:34:56.742(-3)?    { Error: tunguska:reactive-aggregate [Error]
I20190814-10:34:56.742(-3)?     at errorClass.<anonymous> (packages/tunguska:reactive-aggregate/aggregate.js:10:27)
I20190814-10:34:56.743(-3)?     at new errorClass (packages/meteor.js:655:17)
I20190814-10:34:56.743(-3)?     at update (packages/tunguska:reactive-aggregate/aggregate.js:136:13)
I20190814-10:34:56.743(-3)?     at ReactiveAggregate (packages/tunguska:reactive-aggregate/aggregate.js:182:3)
I20190814-10:34:56.743(-3)?     at Subscription.<anonymous> (imports/startup/server/publications.js:1527:5)
I20190814-10:34:56.744(-3)?     at packages/matb33_collection-hooks.js:307:21
I20190814-10:34:56.744(-3)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20190814-10:34:56.744(-3)?     at Subscription._handler (packages/matb33_collection-hooks.js:306:28)
I20190814-10:34:56.744(-3)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
I20190814-10:34:56.745(-3)?     at DDP._CurrentPublicationInvocation.withValue (packages/ddp-server/livedata_server.js:1046:15)
I20190814-10:34:56.745(-3)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20190814-10:34:56.745(-3)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1044:51)
I20190814-10:34:56.745(-3)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:860:9)
I20190814-10:34:56.745(-3)?     at Session.sub (packages/ddp-server/livedata_server.js:625:12)
I20190814-10:34:56.746(-3)?     at packages/ddp-server/livedata_server.js:559:43
I20190814-10:34:56.746(-3)?      isClientSafe: true,
I20190814-10:34:56.746(-3)?      error: 'Error',
I20190814-10:34:56.746(-3)?      reason: 'tunguska:reactive-aggregate',
I20190814-10:34:56.746(-3)?      details: undefined,
I20190814-10:34:56.746(-3)?      message: 'tunguska:reactive-aggregate [Error]',
I20190814-10:34:56.746(-3)?      errorType: 'Meteor.Error' },
I20190814-10:34:56.747(-3)?   errorType: 'tunguska:reactive-aggregate' }
I20190814-10:34:56.747(-3)? Sanitized and reported to the client as: { Error: tunguska:reactive-aggregate [Error]
I20190814-10:34:56.747(-3)?     at errorClass.<anonymous> (packages/tunguska:reactive-aggregate/aggregate.js:10:27)
I20190814-10:34:56.747(-3)?     at new errorClass (packages/meteor.js:655:17)
I20190814-10:34:56.747(-3)?     at update (packages/tunguska:reactive-aggregate/aggregate.js:136:13)
I20190814-10:34:56.747(-3)?     at ReactiveAggregate (packages/tunguska:reactive-aggregate/aggregate.js:182:3)
I20190814-10:34:56.748(-3)?     at Subscription.<anonymous> (imports/startup/server/publications.js:1527:5)
I20190814-10:34:56.748(-3)?     at packages/matb33_collection-hooks.js:307:21
I20190814-10:34:56.748(-3)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20190814-10:34:56.748(-3)?     at Subscription._handler (packages/matb33_collection-hooks.js:306:28)
I20190814-10:34:56.748(-3)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
I20190814-10:34:56.748(-3)?     at DDP._CurrentPublicationInvocation.withValue (packages/ddp-server/livedata_server.js:1046:15)
I20190814-10:34:56.748(-3)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20190814-10:34:56.748(-3)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1044:51)
I20190814-10:34:56.748(-3)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:860:9)
I20190814-10:34:56.749(-3)?     at Session.sub (packages/ddp-server/livedata_server.js:625:12)
I20190814-10:34:56.749(-3)?     at packages/ddp-server/livedata_server.js:559:43
I20190814-10:34:56.749(-3)?   isClientSafe: true,
I20190814-10:34:56.749(-3)?   error: 'Error',
I20190814-10:34:56.749(-3)?   reason: 'tunguska:reactive-aggregate',
I20190814-10:34:56.749(-3)?   details: undefined,
I20190814-10:34:56.749(-3)?   message: 'tunguska:reactive-aggregate [Error]',
I20190814-10:34:56.749(-3)?   errorType: 'Meteor.Error' }
```

**Comment by ShaggyKris** [comment]
@robfallows 

Seems to work on Galaxy! Thank you so much :D

**Comment by robfallows** [comment]
Cool - I'll fix the typos, merge and release.

Thanks for testing 🙂

**Pull request merged**
